name: deploy-prod

on:
  push:
    branches: ['prod']

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      aws-environment: prod
      ref: prod  # git branch to check out
  aws-deploy:
    needs: test
    permissions:
      contents: read
      id-token: write
    uses: "./.github/workflows/aws-deploy.yaml"
    with:
      role-to-assume: "arn:aws:iam::681175625864:role/sagebase-github-oidc-modeladexplorer-infra"
      role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
      aws-environment: prod
