name: deploy-dev

on:
  push:
    branches: ['dev']

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      environment: dev
  aws-deploy:
    uses: "./.github/workflows/aws-deploy.yaml"
    with:
      role-to-assume: "arn:aws:iam::607346494281:role/sagebase-github-oidc-modeladexplorer-infra"
      role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
      environment: dev
