name: deploy-prod

on:
  push:
    branches: ['prod']

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      environment: prod
  aws-deploy:
    uses: "./.github/workflows/aws-deploy.yaml"
    with:
      role-to-assume: "arn:aws:iam::XXXXXXXX:role/sagebase-github-oidc-myapp-infra"
      role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
      environment: prod
