name: deploy-stage

on:
  push:
    branches: ['stage']

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      environment: stage
  aws-deploy:
    uses: "./.github/workflows/aws-deploy.yaml"
    with:
      role-to-assume: "arn:aws:iam::681175625864:role/sagebase-github-oidc-modeladexplorer-infra"
      role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
      environment: stage
