name: test

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run unit tests
        run: python -m pytest tests/ -s -v
  synth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Generate cloudformation
        env:
          ENV: ${{ inputs.environment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cdk synth --debug --output ./cdk.out
